// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqHOX3uqpm0N8nvRiMuqvX6vmdaV27ODo',
    appId: '1:58564698490:web:0ac6ad52683262bb3a36c3',
    messagingSenderId: '58564698490',
    projectId: 'shopping-cart-ef9af',
    authDomain: 'shopping-cart-ef9af.firebaseapp.com',
    storageBucket: 'shopping-cart-ef9af.appspot.com',
    measurementId: 'G-E6QPZQDCWR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3unvS8yjI3VUf3M9OQh7wmJGPLUwi3qI',
    appId: '1:58564698490:android:eac36daf50f4ab943a36c3',
    messagingSenderId: '58564698490',
    projectId: 'shopping-cart-ef9af',
    storageBucket: 'shopping-cart-ef9af.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRLdkJvVguWB2ThWtcC-iju95MUmJmNjY',
    appId: '1:58564698490:ios:f316cd990782c9b83a36c3',
    messagingSenderId: '58564698490',
    projectId: 'shopping-cart-ef9af',
    storageBucket: 'shopping-cart-ef9af.appspot.com',
    iosBundleId: 'com.example.shoppingCartExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRLdkJvVguWB2ThWtcC-iju95MUmJmNjY',
    appId: '1:58564698490:ios:f316cd990782c9b83a36c3',
    messagingSenderId: '58564698490',
    projectId: 'shopping-cart-ef9af',
    storageBucket: 'shopping-cart-ef9af.appspot.com',
    iosBundleId: 'com.example.shoppingCartExample',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqHOX3uqpm0N8nvRiMuqvX6vmdaV27ODo',
    appId: '1:58564698490:web:9b06f1f02d1fcf343a36c3',
    messagingSenderId: '58564698490',
    projectId: 'shopping-cart-ef9af',
    authDomain: 'shopping-cart-ef9af.firebaseapp.com',
    storageBucket: 'shopping-cart-ef9af.appspot.com',
    measurementId: 'G-HFDBT5EE9C',
  );

}